### ISSUE TITLE
Add huge burst lasers

### ISSUE THREAD

**Issue by damonbrodie** [cmmcleod/coriolis-data#18] opened 2016-07-07 13:55 UTC
Latest patch added huge burst lasers.  Here's the data that I collected and used to add to Ocellus:

```
        case "128049403":
            module.@class = "4";
            module.rating = "E";
            module.category = "hardpoint";
            module.mount = "Fixed";
            module.name = "Burst Laser";
            break;
        case "128727920":
            module.@class = "4";
            module.rating = "E";
            module.category = "hardpoint";
            module.mount = "Gimballed";
            module.name = "Burst Laser";
            break;
```

**Comment by Marginal** [comment] 2016-07-07 14:06
Duplicate of #16

**Closed as completed** 2024-07-25 20:26 UTC
